### ISSUE TITLE
Request for cox model

### ISSUE THREAD

**Issue by amymariemason** [amymariemason/SUMnlmr#25]
Cox model option for G-Y in the create_summary_nlmr function

**Comment by ayodipupo** [comment]
Thanks for this Amy. I can't seem to find the cox model option in the create_summary_nlmr function as shown below:
create_nlmr_summary(
  y,
  x,
  g,
  covar = NULL,
  family = "gaussian",
  controlsonly = FALSE,
  q,
  strata_method = "residual",
  strata_bound = c(0.2, 0.1, 0.8, 0.9),
  extra_statistics = FALSE,
  report_GR = FALSE,
  report_het = FALSE,
  seed = 1234
)
I'lll be grateful if you can signpost to how to specify Cox PH model using this!

**Comment by amymariemason** [comment]
Sadly I have still not had time to implement it as a defined option. It is very much on my wish list! 

You could make your own -   you just need to adjust the G-Y model in the function that creates the summarized version: lines 160 – 196 in the create_nlmr_summary where it is defining model (model2 is the G-X regression).

Alternatively, run the start of the function as is to find the strata and G-X beta estimates, then use the list of which person is in which strata (x0q) to run cox models in each strata separately to get the G-Y estimates and replace them into the array. Once you've got the beta estimates and s.e for G-Y you can run the model fitting functions as usual

**Comment by amymariemason** [comment]
There is a now a coxph option for the G-Y model - please let me know if you find any issues with it!

**Comment by ayodipupo** [comment]
Thanks so much Amy!
________________________________
