### ISSUE TITLE
Graph outputs

### ISSUE THREAD

**Issue by amymariemason** [amymariemason/SUMnlmr#26]
(emailled request)

However, I realised that the graph function reports the causal effect on y-axis as the coefficient ie logOR and not the OR.
Do you have any idea how to configure the function to plot ORs and not coefficients on the y-axis?

**Comment by amymariemason** [comment]
Could you give me more details on what settings you are using?  
Both the piecewise and the fractional polynomial method should be applying exponential functions before plotting when using family="binomial"

**Comment by amymariemason** [comment]
The graph function should be plotting OR not logOR if you have it set to family = "binomial" for both piecewise and fractional, so I do want to track down what is going wrong here - can you give me more details on 
*which function 
*what settings 
*lace estimates output  (contained in model list as array called lace)
*graph plotted

In general, the output is a ggplot object, so you can always pull the data back out and replot it
for example
  test_data<-LDL_CAD
  model <-with(LDL_CAD, piecewise_summ_mr(by, bx, byse, bxse, xmean, xmin,xmax,
                                          ci="bootstrap_se",
                                          nboot=1000,
                                          fig=TRUE,
                                          family="gaussian",
                                          ci_fig="ribbon",
                                          average.exposure.associations = TRUE)
  )
model$figure$plot_env$plot_data  # <- estimates for end-points of each strata
model$figure$plot_env$plot_data1  # <- estimates for mid-point of each strata
model$figure$plot_env$plot_data2  # <- reference point

**Comment by ayodipupo** [comment]
Thanks so much Amy. This works.
I noticed that the heterogeneity test option model$p_heterogeneity returns no result.
Does the package no longer support it?

**Comment by amymariemason** [comment]
Because of the issues with violation of the constant heterogeneity assumption, I moved the heterogeneity tests to the create_nlmr_summary function under the report_het function.
See https://www.medrxiv.org/content/10.1101/2022.10.26.22280570v1.full-text for why checking this early in the process is important.
