### ISSUE TITLE
multiple IVs for create_nlmr_summary

### ISSUE THREAD

**Issue by sunyeoplee** [amymariemason/SUMnlmr#28]
Hello, 

It seems to me that create_nlmr_summary function only takes one IV (a SNP or a genetic score built from multiple SNPs). Or have I not understood the function correrctly? Is there a way to include multiple IVs in the function? If not, this can be a good addition to the function!

Thanks,

Sun

**Comment by amymariemason** [comment]
You have understood the package function correctly, there is no way to input multiple SNPs directly.

However using genetic score as a single instrument should be equivalent to fitting TSLS estimate to multiple SNP instruments when the weights are taken from the same dataset (https://onlinelibrary.wiley.com/doi/full/10.1002/sim.6835 ) and also allows for user fitting weights from an external GWAS if desired. 

I am unlikely to implement taking multiple SNPs as input, unless there is a use case for it that I have missed?
