### ISSUE TITLE
Recognising 'coxph' family

### ISSUE THREAD

**Issue by fewbank** [amymariemason/SUMnlmr#30]
Firstly, thank you very much for this package. I have been experiencing issues when trying to use survival data as it is not recognising coxph. The script has been returning the following error: 

Error in create_nlmr_summary(y = new.y, x = test_data$X, g = test_data$g,  : 
  family must be gaussian or binomial

This appears to be the case when I'm using your test data.

**Comment by amymariemason** [comment]
Can I just check if you've updated the package since the weekend? I only added the coxph functionality on Friday, so earlier downloads won't recognise the command.

**Comment by fewbank** [comment]
Just updated the package and it works! Many thanks again.
